#!/usr/bin/env bash
# This script transfers file to a host server using scp

if [ "$#" -lt 4 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

if [ "$4" ]; then
	scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3@$2:~/"
elif [ "$3" ]; then
	scp -o StrictHostKeyChecking=no "$1" "$3@$2:~/"
fi
