#!/usr/bin/env bash

# This script transfers file to a host server using scp

if [ "$#" -lt 3 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

FILE_PATH="$1"
IP="$2"
USERNAME="$3"

if [ "$4" ]; then
	scp -o StrictHostKeyChecking=no -i "$FILE_PATH" "$USERNAME@$IP:~/"
elif [ "$3" ]; then
	scp -i "$4" -o StrictHostKeyChecking=no "$FILE_PATH" "$USERNAME@$IP:~/"
fi
