#!/usr/bin/env bash
# This script installs nginx on a server.

apt-get update
apt-get install -y nginx
sudo ufw allow "Nginx Full"
echo 'Hello World!' | sudo tee /var/www/html/index.nginx-debian.html > /dev/null
service nginx restart
