#!/usr/bin/env bash
# This script installs nginx on a server.

apt-get update
apt-get install -y nginx
ufw allow "Nginx Full"
echo 'Hello World!' | sudo tee /var/www/html/index.nginx-debian.html > /dev/null
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404.html
sudo sed -i '/listen 80 default_server/a location /redirect_me {\n    return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n}' /etc/nginx/sites-available/default
sudo sed -i '/listen 80 default_server/a error_page 404 /404.html;\n \tlocation = /404.html {\n \t\troot /usr/share/nginx/html; \n\t\tinternal;\n    \t}' /etc/nginx/sites-available/default
service nginx restart
