#!/usr/bin/env bash
# This script configures HAProxy for a server.

apt-get update
apt-get -y install haproxy
# apt-get install --no-install-recommends software-properties-common
# add-apt-repository ppa:vbernat/haproxy-2.6
# apt-get install haproxy=2.6.\*
cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak
cat <<EOL | sudo tee -a /etc/haproxy/haproxy.cfg
frontend http-in
	bind *:80
	mode http
	default_backend servers

backend servers
	balance roundrobin
	server 281110-web-01 34.207.57.13:80 check
	server 281110-web-02 54.174.203.20:80 check
EOL
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
service haproxy restart
