#!/usr/bin/env bash
# This script  displays all active IPv4 IPs.

ip_addresses=$(ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | awk '{print $2}' | cut -d':' -f2)

for ip in $ip_addresses
do
	echo "$ip"
done
